### ISSUE TITLE
AWS Lambda Package Size Issues

### ISSUE THREAD

**Issue by omalave** [erenyasarkurt/OpenAI-AWS-Lambda-Layer#4]
Hi!

I just testing a layer for py 3.9 and Im getting this error:

```
CREATE_FAILED: GenerateUnderscorecontentLambdaFunction (AWS::Lambda::Function)
Resource handler returned message: "Unzipped size must be smaller than 131361085 bytes (Service: Lambda, Status Code: 400, Request ID: ff99b84d-5647-4bc4-812d-b87b708c36b5)" (RequestToken: fc4c4c5b-e137-9b36-93ad-e5394fcd22c3, HandlerErrorCode: InvalidRequest)
```

And in python requirements I have this settings:

```
  pythonRequirements:
    pythonBin: python3
    slim: true
    zip: true
```

Any help?
